console.log($(".is-preload"));
console.log($(".is-preload").children());
console.log($("#header").children());
console.log($(".logo").children());
var nav = $("#header").next();
console.log($("#header").next().children());
var navUl = nav.children();
console.log(navUl.children().children());
var main = $(".main");
console.log(main.children());
console.log($(".major").children());
console.log($(".content").children());
console.log($(".content"));
console.log($(".spotlight").children());
console.log($(".actions").children());
console.log($(".button").children());
console.log($(".image").children());
console.log($("li").children());
console.log($(".features").children());
console.log($(".statistics").children());
console.log($("#footer").children());
console.log($("section").children());
console.log($(".alt").children());
console.log($("dd").children());
console.log($(".icons").children());